### ISSUE TITLE
dtd is outdated

### ISSUE THREAD

**Issue by jto** [spotify/spotify-checkstyle-config#26]
DTD is outdated which causes sbt-checkstyle to fail with the following exception:

<details><summary>Exception</summary>

```
[error] java.io.FileNotFoundException: http://www.puppycrawl.com/dtds/configuration_1_3.dtd
[error]         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
[error]         at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[error]         at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
[error]         at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
[error]         at java.security.AccessController.doPrivileged(Native Method)
[error]         at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[error]         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1304)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1270)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:264)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1161)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1045)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:959)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
[error]         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
[error]         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
[error]         at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[error]         at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
[error]         at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[error]         at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
[error]         at scala.xml.factory.XMLLoader.loadXML(XMLLoader.scala:41)
[error]         at scala.xml.factory.XMLLoader.loadXML$(XMLLoader.scala:37)
[error]         at scala.xml.XML$.loadXML(XML.scala:60)
[error]         at scala.xml.factory.XMLLoader.loadString(XMLLoader.scala:60)
[error]         at scala.xml.factory.XMLLoader.loadString$(XMLLoader.scala:60)
[error]         at scala.xml.XML$.loadString(XML.scala:60)
[error]         at com.etsy.sbt.checkstyle.Checkstyle$.checkstyle(Checkstyle.scala:35)
[error]         at com.etsy.sbt.checkstyle.CheckstylePlugin$autoImport$.$anonfun$checkstyleTask$1(CheckstylePlugin.scala:36)
[error]         at com.etsy.sbt.checkstyle.CheckstylePlugin$autoImport$.$anonfun$checkstyleTask$1$adapted(CheckstylePlugin.scala:34)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

</details>

In https://github.com/spotify/spotify-checkstyle-config/blob/master/src/main/resources/spotify_checks.xml#L2-L4, http://www.puppycrawl.com/dtds/configuration_1_3.dtd does not exist anymore, the correct URL is https://checkstyle.org/dtds/configuration_1_3.dtd.

**Comment by rculbertson** [comment]
Fixed in #27
